package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v2"
)

const swaggerTemplate = `// Code generated by swagger-generator. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

var doc = ` + "`{{.JSON}}`" + `

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "{{.Version}}",
	Host:        "{{.Host}}",
	BasePath:    "{{.BasePath}}",
	Schemes:     []string{{.Schemes}},
	Title:       "{{.Title}}",
	Description: "{{.Description}}",
}

func init() {
	swag.Register(swag.Name, &swag.Spec{
		InfoInstanceName: "swagger",
		SwaggerTemplate: doc,
	})
}
`

func main() {
	// Read the OpenAPI spec
	specPath := filepath.Join("docs", "swagger.yaml")
	specData, err := ioutil.ReadFile(specPath)
	if err != nil {
		log.Fatalf("Failed to read OpenAPI spec: %v", err)
	}

	// Parse the YAML into a map
	var yamlData map[interface{}]interface{}
	if err := yaml.Unmarshal(specData, &yamlData); err != nil {
		log.Fatalf("Failed to parse OpenAPI spec: %v", err)
	}

	// Convert to string map
	spec := toStringMap(yamlData)

	// Extract info
	info := spec["info"].(map[string]interface{})
	servers := spec["servers"].([]interface{})
	server := servers[0].(map[string]interface{})

	// Prepare template data
	data := struct {
		JSON        string
		Version     string
		Host        string
		BasePath    string
		Schemes     string
		Title       string
		Description string
	}{
		JSON:        string(specData),
		Version:     info["version"].(string),
		Host:        strings.TrimPrefix(server["url"].(string), "http://"),
		BasePath:    "/api/v1",
		Schemes:     "[]string{\"http\", \"https\"}",
		Title:       info["title"].(string),
		Description: info["description"].(string),
	}

	// Create docs directory if it doesn't exist
	if err := os.MkdirAll("docs", 0755); err != nil {
		log.Fatalf("Failed to create docs directory: %v", err)
	}

	// Generate the docs file
	tmpl, err := template.New("swagger").Parse(swaggerTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	file, err := os.Create("docs/swagger.go")
	if err != nil {
		log.Fatalf("Failed to create swagger.go: %v", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	fmt.Println("Swagger documentation generated successfully!")
}

// Convert interface{} to map[string]interface{}
func toStringMap(i interface{}) map[string]interface{} {
	switch x := i.(type) {
	case map[interface{}]interface{}:
		m := map[string]interface{}{}
		for k, v := range x {
			switch k2 := k.(type) {
			case string:
				switch v2 := v.(type) {
				case map[interface{}]interface{}:
					m[k2] = toStringMap(v2)
				case []interface{}:
					m[k2] = toStringSlice(v2)
				default:
					m[k2] = v2
				}
			}
		}
		return m
	default:
		return nil
	}
}

// Convert []interface{} to []map[string]interface{}
func toStringSlice(s []interface{}) []interface{} {
	var result []interface{}
	for _, v := range s {
		switch v2 := v.(type) {
		case map[interface{}]interface{}:
			result = append(result, toStringMap(v2))
		case []interface{}:
			result = append(result, toStringSlice(v2))
		default:
			result = append(result, v2)
		}
	}
	return result
} 